#!/bin/sh -e

sed -i 's/^CC = .*/CC = cproc/' config.mk
sed -i 's/^LDFLAGS = .*/LDFLAGS = -static/' config.mk
sed -i 's/^YACC = .*/YACC = byacc/' config.mk
sed -i 's/volatile sig_atomic_t/sig_atomic_t/' make/make.h
sed -i 's/volatile sig_atomic_t/sig_atomic_t/' make/main.c

make sbase-box
make PREFIX=/usr DESTDIR="$1" sbase-box-install
