#!/bin/sh -e

sed -i "s/CC = cc/CC = cproc/" config.mk || true
sed -i "s/LDFLAGS  =/LDFLAGS  = -static/" config.mk || true

make CC="${CC:-cproc}" LDFLAGS="-static"
make CC="${CC:-cproc}" PREFIX=/usr DESTDIR="$1" install
